USE Clientes
GO

IF EXISTS(SELECT TOP 1 * FROM SYS.OBJECTS WHERE NAME = 'BuscaCPF')
BEGIN
    DROP PROCEDURE BuscaCPF
    PRINT 'BuscaCPF -- REMOVIDA COM SUCESSO'
END
GO

CREATE PROCEDURE dbo.BuscaCPF
(
@CPF varchar(11)
)
AS
BEGIN

SET NOCOUNT ON
-----------------

SELECT * FROM Cliente Where CPF = @CPF;

-----------------
END
GO

IF EXISTS(SELECT TOP 1 * FROM SYS.OBJECTS WHERE NAME = 'BuscaCPF')
BEGIN
    PRINT 'BuscaCPF -- CRIADA COM SUCESSO'
END
GO